config/routes.rb
Rails.application.routes.draw do
  
  
  resources :profiles, as: :users, only: [:show, :update]
  
  #devise_for :users, controllers: {registrations: "registrations"}
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  #Redireccionar c a companies
  get '/c/:id', to: redirect('/companies/%{id}')
  
  resources :companies do
  	resources :cards do
      resources :transactions
    end
    #Entorno de trabajo
    get 'panel', to: 'cards#scan'
    post 'panel', to: 'cards#scan'
    get 'prueba', to: 'companies#freeTrial'
    get 'stats', to: 'companies#stats'
    get 'requestCard', to: 'companies#send_mail_card_request'
  
  end

  #Ruta para asignar usuario a tarjeta existente
  post 'asignar', to: 'cards#asignuser'
  

  #Mostrar INDEX si está logueado
  authenticated :user do
  	root 'main#index'
  end
  
  #Mostrar página de aterrizaje si no está logueado
  unauthenticated :user do
  	devise_scope :user do
  		root 'main#landing'
  	end
  end

  #Rutas dinámicas para nombres de usuario de las compañías
  #datos = Company.all
  
  #datos.each do |c|
    #A menos que el alias esté vacío...
  #  unless c.alias == nil
  #    get c.alias, to: 'companies#show', :id => c.id    
  #  end
  #end
  

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :company
  validates :number, length: { is: 9 }

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]
  #Admin sin restricciones
  before_action :authenticate_admin!, only: [:destroy]
  #Dueño de compañía A, NEW y CREATE
  before_action :authenticate_owner!, only: [:index, :new, :create, :edit, :update, :scan]
  #Empleado de compañía A, SHOW, INDEX y EDIT de compañía A.
  #Cliente, SHOW, pidiendo el PIN si el USUARIO es NIL. Si no, autenticar y SHOW sólo de sus tarjetas asociadas.


  # GET /cards
  # GET /cards.json
  def index
    set_company
    verify_own_id
    
    #Orden por defecto
    filtro = 'client'
    # Ordenamiento
    if(params[:order]=="asc")
      if(params[:field]=="name")
        filtro = 'user'
      end
      if(params[:field]=="cardNumber")
        filtro = 'number'
      end
      if(params[:field]=="amount")
        filtro = 'credit1'
      end
      if(params[:field]=="score")
        filtro = 'credit2'
      end  
          
    end
    if(params[:order]=="desc")
      if(params[:field]=="name")
        filtro = 'user DESC'
      end
      if(params[:field]=="cardNumber")
        filtro = 'number DESC'
      end
      if(params[:field]=="amount")
        filtro = 'credit1 DESC'
      end
      if(params[:field]=="score")
        filtro = 'credit2 DESC'
      end  
            
    end
    
    
    if(params[:soloactivas])
        @cards = Card.where(company_id: @company, status: "1").order(filtro).paginate(:page => params[:page], :per_page => 20)
        message = filtro
    else
        @cards = Card.where(company_id: @company).order(filtro).paginate(:page => params[:page], :per_page => 20)
        message = filtro
    end


    @users = User.all

    #Requires para generar códigos de barra
    require 'barby'
    require 'barby/barcode/ean_13'
    require 'barby/outputter/png_outputter'
    
    #Exportar a xlsx

    respond_to do |format|
      format.html
      #format.csv { send_data @cards.to_csv }
      format.xlsx { render xlsx: "index.xlsx"}
    end
  end

  def asignuser
    
    #Tomar params num y pin
    num = params[:num]
    pin = params[:pin]
    num.to_s
    #Verificar cantidad de dígitos
    if num.length==13
      if pin.to_s.length==4
        #Descomponer el número de tarjeta
        country=num[0..2].to_i
        number=num[3..11]
        #Consultar BD buscando la tarjeta
        card=Card.find_by(country: country, number: number)
        #Si no hay resultados, devolver error
        unless card==nil
          #Si hay resultado, verificar que la tarjeta no tenga otro usuario asignado
          if card.user==nil
            #Si todo lo anterior está bien, verificar que el pin sea el correcto
            pin.to_i
            if pin.to_s == card.pin.to_s
              card.user= current_user.id
              if card.save
                redirect_to root_path, notice: "Asignaste usuario a tu nueva tarjeta"
              else
                redirect_to root_path, notice: "**Tus datos son correctos pero ocurrió un error. Contactá con el administrador"
              end
            else
              redirect_to root_path, notice: "**Pin incorrecto"
            end


          else
            #Esta tarjeta tiene otro usuario asignado
            redirect_to root_path, notice: "**Esta tarjeta ya tiene un usuario asignado"
          end
          
        else
          #No existe esa tarjeta
          redirect_to root_path, notice: "**No existe esa tarjeta."
        end
        
      else
        #Pin inválido
        redirect_to root_path, notice: "**Pin inválido"
      end
    else
      #Num inválido
      redirect_to root_path, notice: "**Número de tarjeta inválido"
    end
    

  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    set_company
    unless @company.id == @card.company_id
      redirect_to root_path, notice: "**COMPAÑÍA INVÁLIDA"
      
    end
    @transaction = Transaction.new
    unless @card.user == nil
      @usuario = User.find(@card.user)
    end

  end

  # GET /cards/new
  def new
    set_company
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def createlik
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
#QUITAR ESTO CUANDO SE AUTOMATICE LA TAREA DE CRACIÓN DE TARJETAS
    unless current_user.is_admin?

      redirect_to root_path, notice: "**Por el momento no estás autorizado a realizar esta tarea."
    else


    # Variables del hash: "cant",  "type" ("tabla","impresion" o "encargo"), "commit"=>"Crear", "company_id"
    set_company
    create_params
    

    # Validar cantidad
    unless @cant<0 || @cant>1000
      # Repetir cantidad desde CLIENTCOUNT+1 hasta CLIENTCOUNT+1+CANT
      inicio=@company.clientcount+1
      fin=inicio+@cant-1
        buenas=0
        malas=0
      for i in inicio..fin
        card = Card.new
        card.company_id = @company.id
        card.credit1 = 0
        card.credit2 = 0
        card.credit2_enabled = false
      # Armar CLIENT(i) y NUMBER (CO,CO,CO,CO,CL,CL,CL,CL,CL)
        card.client = i
        #Llevar CLIENT a 5 caracteres
        cl=i.to_s

        unless cl.length==5
            begin
                cl="0"+cl
            end until cl.length==5
        end

        #Llevar COMPANY a 4 caracteres
        co=@company.id.to_s

        unless co.length==4
            begin
                co="0"+co
            end until co.length==4
        end

        card.number=co+cl
      # Generar PIN aleatorio
        card.pin = rand(1000..9999)

        #Cambiar STATUS según opción elegida

        # Si se guarda, avisar, si no ... también

          if card.save
            buenas=buenas+1
            @company.clientcount=@company.clientcount+1
            @company.save
          else
            malas=malas+1
          end
        end       
        redirect_to company_cards_path, notice: "Se terminó el proceso... 
        Tarjetas exitosas: " + buenas.to_s + " | Tarjetas malas: " + malas.to_s + " | Empezando desde el ID: " + inicio.to_s + " hasta : " + fin.to_s

    end

  end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    set_company
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to company_card_path(@company,@card), notice: 'Tarjeta actualizada' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to company_cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def scan
    set_company
    query_present

    mobile_param

    if @q.present?
      #Paso 2: Consultar tarjeta
      @paso=2
      @q.to_s

      if @q.length==13

        card_number=@q[3,9] 
        card_company= card_number[0,4].to_i

        #CONSULTAR CLIENTE por QUERY a columna NUMBER
        if card_company == @company.id
          @card = Card.find_by number: card_number
          if @card == nil
            @error = "**El número de cliente de la tarjeta es inválido"
          else
            redirect_to company_card_path(@company,@card)
          end
        else
          @error = "**La tarjeta no pertenece a esta compañía"
        end
      else
        
        if @q.length<5
          #Llevar company.id a 4 dígitos
          co=@company.id.to_s
          unless co.length==4
              begin
                  co="0"+co
              end until co.length==4
          end

          

          #Llevar CLIENT a 5 caracteres
          cl=@q.to_s

          unless cl.length==5
              begin
                  cl="0"+cl
              end until cl.length==5
          end

          card_number=co+cl;

          @card = Card.find_by number: card_number
            if @card == nil
              @error = "**El número de cliente de la tarjeta es inválido"
            else
              redirect_to company_card_path(@company,@card)
            end
        else       
          @error = "**Número inválido"
        end
      end

    else

        #Paso 1: Definir tarjeta de la cual se quiere debitar o acreditar
        @paso=1

    end


  end

  def movimiento
    set_card
    set_company
    credit=params[:credit].to_i
    debit=params[:debit].to_i

    nuevocred=@card.credit1+cred-deb
    @card.credit1=nuevocred
    @card.Save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end
    def create_params
      @cant = params["cant"].to_i
      type = params[:type]
    end
    def asign_params
      num = params[:num]
      pin = params[:pin]
    end
    def set_company
      @company = Company.find(params[:company_id])      
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:user, :country, :credit1, :credit2, :status, :credit2_enabled, :client)
    end
        def verify_own_id
      unless (@company.admin == current_user.id)
        unless current_user.is_admin?
           redirect_to root_path
        end
      end
    end
    def query_present
      @q=params[:q]
    end
    def mobile_param
      if params[:mobile].to_s == 'true'
        @mobile = true
      else
        @mobile = false
      end
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.erb
      
    <% @cards.each do |card| %>
      <tr>
        <td><% cod = card.country.to_s + card.number.to_s %><%= cbar = Barby::EAN13.new(cod) %></td>
        <td><img src="<%= cbar.to_image.to_data_url %>"></td>
        <td><%= card.pin %></td>
        <td><% unless card.user==nil %>
          <% unless @users.find_by(id: card.user).name==nil || @users.find_by(id: card.user).last_name==nil%>
          <%=  @users.find_by(id: card.user).name + " " + @users.find_by(id: card.user).last_name%>
            <% else %>
            Sin nombre
            <% end %>
            
            <% else %>

            No registrado

            <% end %>

          </td>
        <td><%= card.credit1 %></td>
        <td><%= card.status %></td>
        <td><%= link_to 'Movimientos', company_card_transactions_path(@company,card) %></td>
        <td><%= link_to 'Cargar', company_card_path(@company,card) %></td>
        <td><%= link_to 'Cambiar estado', edit_company_card_path(@company,card) %></td>
        <% #<td><%= link_to 'Destroy', [@company,card], method: :delete, data: { confirm: 'Are you sure?' } %>
      </tr>
    <% end %>

app/views/cards/_form.haml
.row.center-xs
  .col.s12.m6
    .card.center
      .card-content
        .card-title
          %h2 SALDO ACTUAL
        .card-actions
          %i.material-icons.medium monetization_on
          %span.money
            = @card.credit1
  .col.s12.m6
    .card
      .card-content

        .card-title
          %h2 ESTADO
          =form_for @card, :url => {:action => "update"} do |form|
            .row.center-xs
              -# = form.label(:status, "Estado (INGRESE 1 PARA ACTIVAR)")
              -# = form.text_field(:status)
              .input-field.col.s12.fixed
                = form.radio_button(:status, "0")
                = form.label(:status_0, "Inactiva")
              .input-field.col.s12.fixed
                = form.radio_button(:status, "1")
                = form.label(:status_1, "Activada")
              .input-field.col.s12.fixed
                = form.radio_button(:status, "2")
                = form.label(:status_2, "Robada / Perdida")
              -if current_user.is_admin?
                .input-field.col.s12.fixed
                  = form.radio_button(:status, "3")
                  = form.label(:status_3, "En proceso de impresión / Enviada")                  
                .input-field.col.s12.fixed
                  = form.radio_button(:status, "4")
                  = form.label(:status_4, "Enviada e inactiva") 
            = form.submit "Modificar", :class=> "btn"

app/views/cards/edit.haml
.container
  .row
    .card
      %h1.center
        Cambiar estado
      = render 'form', card: @card
      .center
        = link_to 'Descartar cambios', company_card_path, :class=> "btn"

app/views/cards/index.html.erb
<div class="container white">
  <h1 class="center">Gestión de tarjetas y Clientes</h1>
<div class="row center-xs">
<% if params[:soloactivas] %>
  <div class="switch row">
  <i class="material-icons">credit_card</i>Tarjetas inactivas: 
    <label>
      Ocultar
      <a href="?"><input type="checkbox" id="mcb">
      <span class="lever"></span></a>
      Mostrar
    </label>
  </div></div>

<% else %>

  <div class="switch row">
  <i class="material-icons">credit_card</i>Tarjetas inactivas: 
    <label>
      Ocultar
      <a href="?soloactivas=true"><input type="checkbox" id="mcb" checked="checked">
      <span class="lever"></span></a>
      Mostrar
    </label>
  </div></div>
<% end %>
<div class="row center-xs"><%= will_paginate @cards %></div>


<table class="striped">
  <thead>
    <tr>
      <th>Número de tarjeta 

        <a href="?&order=asc&field=cardNumber"><i class="material-icons tooltipped" data-tooltip="Ordenar ascendentemente">arrow_drop_up</i></a>
        <a href="?&order=desc&field=cardNumber"><i class="material-icons tooltipped" data-tooltip="Ordenar descendentemente">arrow_drop_down</i></a>

      </th>
      <!-- <th>Código de barras</th> -->
      <th>Pin</th>
      <th>Apellido y nombre
        <a href="?&order=asc&field=name"><i class="material-icons tooltipped" data-tooltip="Ordenar ascendentemente">arrow_drop_up</i></a>
        <a href="?&order=desc&field=name"><i class="material-icons tooltipped" data-tooltip="Ordenar descendentemente">arrow_drop_down</i></a>
      </th>
      <th>Saldo
        <a href="?&order=asc&field=amount"><i class="material-icons tooltipped" data-tooltip="Ordenar ascendentemente">arrow_drop_up</i></a>
        <a href="?&order=desc&field=amount"><i class="material-icons tooltipped" data-tooltip="Ordenar descendentemente">arrow_drop_down</i></a>
      </th>
      <th>Puntaje
        <a href="?&order=asc&field=score"><i class="material-icons tooltipped" data-tooltip="Ordenar ascendentemente">arrow_drop_up</i></a>
        <a href="?&order=desc&field=score"><i class="material-icons tooltipped" data-tooltip="Ordenar descendentemente">arrow_drop_down</i></a>
      </th>
      <th>Estado de la tarjeta
      </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% unless @cards.count== %>
    <% @cards.each do |card| %>
      <tr>
        <td class="tooltipped" data-tooltip="Núm. de cliente: <%= card.client %>"><% cod = card.country.to_s + card.number.to_s %><%= cbar = Barby::EAN13.new(cod) %></td>
        <!--<td><img src="<%= cbar.to_image.to_data_url %>"></td> -->
        <td class="tooltipped" data-tooltip="<%= card.pin %>"><i class="material-icons">security</i></td>
        <td class="tooltipped" data-tooltip="ID. Praemium: <%= card.user %>"><% unless card.user==nil %>
          <% unless @users.find_by(id: card.user).name==nil || @users.find_by(id: card.user).last_name==nil%>
          <%=  @users.find_by(id: card.user).name + " " + @users.find_by(id: card.user).last_name%>
            <% else %>
            Sin nombre
            <% end %>
            
            <% else %>
              No registrado
            <% end %>

          </td>
        <td>$ <%= (card.credit1.to_f)/100 %></td>
        <td> <%= card.credit2%></td>
        <td><%= card.status %>
                <% if card.status == 1 %>
                  - ACTIVADA
                <% end %>
                <%if card.status == 2 %>
                  - ROBADA/ PERDIDA
                <% end %>
                <% if card.status == 3 %>
                  - EN PROCESO DE FABRICACIÓN / ENVÍO
                <% end %>
                <% if card.status == 4 %>
                  - ENTREGADA E INACTIVA
                <% end %>
                <% if card.status == 0 %>
                  - INACTIVA
                <% end %> 
</td>



        <td><%= link_to raw('<i class="large mdi-navigation-menu material-icons"> view_headline</i>'), company_card_transactions_path(@company,card), :class => "btn-large black tooltipped", "data-tooltip"=>"Ver movimientos"  %></td>
        <td><%= link_to raw('<i class="large mdi-navigation-menu material-icons"> monetization_on</i>'), company_card_path(@company,card), :class => "btn-large black tooltipped", "data-tooltip"=>"Recargar o Comprar"  %></td>
        <td><%= link_to raw('<i class="large mdi-navigation-menu material-icons"> offline_pin</i>'), edit_company_card_path(@company,card), :class => "btn-large black tooltipped", "data-tooltip"=>"Cambiar estado (robada, perdida, activa, inactiva)" %></td>
        <% #<td><%= link_to 'Destroy', [@company,card], method: :delete, data: { confirm: 'Are you sure?' } %>
      </tr>
    <% end %>
<% end %>
  </tbody>
</table>
<div class="row center-xs"><%= will_paginate @cards %></div>

</div>
<br>

<%= link_to 'Menú de gestión de empresa', company_path(@company), :class=> "btn" %>
<p>
  Descarga:
  <%= link_to "Excel", company_cards_path(format: "xlsx") %>
</p>

app/views/cards/new.haml
.container
  .row
    .card
      .card-content
        .card-title
          %h1.center
            =@company.name
        .row
          .col.s12.m8
            %h2 Crear tarjetas
            %subtitle En esta sección se crearán las tarjetas, pero por defecto estarán INHABILITADAS. Para habilitar una tarjeta, haga una primera carga de saldo (escaneando su código de barras desde el entorno de trabajo).
        .row
          .col.s12.m8
            = form_tag company_cards_path, action: :create do
              %p
                = label_tag(:idi, "ID de cliente Inicial:")
                = label_tag(:idi, @company.clientcount+1)
              %p
                = label_tag(:cant, "Cantidad de TARJETAS a crear:")
                = text_field_tag(:cant)

              %p
                = radio_button_tag(:type, "encargo")
                = label_tag(:type_encargo, "Encargar impresión de tarjetas (20 días hábiles para su entrega / Costo: $25 por tarjeta")
              %p
                = radio_button_tag(:type, "tabla")
                = label_tag(:type_tabla, "Exportar archivo de códigos para entregar a imprenta")  
              %p
                = radio_button_tag(:type, "impresion")
                = label_tag(:type_impresion, "Exportar tarjetas en formato PDF.") 
              %p
                = submit_tag(:Crear, :class=> "btn")
        .card-actions         
          = link_to 'Menú de gestión de empresa', company_path(@company)

app/views/cards/scan.haml
:javascript
  function launchFullScreen(element) {
    if(element.requestFullScreen) {
      element.requestFullScreen();
    } else if(element.mozRequestFullScreen) {
      element.mozRequestFullScreen();
    } else if(element.webkitRequestFullScreen) {
      element.webkitRequestFullScreen();
    }
  }
  // Lanza en pantalla completa en navegadores que lo soporten
   function cancelFullScreen() {
       if(document.cancelFullScreen) {
           document.cancelFullScreen();
       } else if(document.mozCancelFullScreen) {
           document.mozCancelFullScreen();
       } else if(document.webkitCancelFullScreen) {
           document.webkitCancelFullScreen();
       }
   }


-unless notice==nil
  -if notice[0,3]=="*T*"
    .container
      .card.green
        %h1.white-text <i class="material-icons">done</i> Transacción correcta

        %strong.white-text
          =raw(notice)



.container
  .row
    
    -if @paso==2	
      -if @error!= nil
        .cajita.col-xs-12.center-xs
          %h1 Se produjo un error:
          %p
            =@error
          %p
            -if @mobile == true
              =link_to "Volver a cargar", company_panel_path(@company, :mobile => true), :class=> "btn lime"
            -else
              =link_to "Volver a cargar", company_panel_path(@company), :class=> "btn lime"
      -else
        %h1 Acredite o debite los puntos correspondientes
        =render 'form', card: @card
      
    -if @paso==1

      .cajita.col-xs-12.center-xs
        .col-xs-12.center-xs
          -if @mobile==true
            %h1 Tome una fotografía al código de barras...
            =render partial: 'file_input'
            %h1 O ingrese el número de cliente
          -else
            :javascript
              setInterval('q()',500);
              console.log('PC');
              function q(){
                document.getElementById("q").focus();
              }
            %h1 Escanee tarjeta o ingrese número de cliente
        .col-xs-12.center-xs
          = form_tag(company_panel_path(@company), method: "get", id: "query") do
            = label_tag(:q, "Ingrese número de tarjeta o número de cliente:")
            = text_field_tag(:q)
            -if @mobile==true
              =hidden_field_tag('mobile', 'true')
            .center
              = submit_tag("Buscar", :class=>"btn")


    -if @paso==3
      %h1 Cargando cambios ...

  .row
    .col-xs-12.center-xs
      = link_to 'Volver', company_path(@company), :class=>"btn"
    
      .right   
        %button{:onclick=>"launchFullScreen(document.documentElement);"}
          %i.material-icons
            fullscreen
        %button{:onclick=>"cancelFullScreen();"}
          %i.material-icons
            fullscreen_exit

app/views/cards/show.haml
.container
  .row
    %h1.center-xs.chip
      =@company.name
  .row.middle-xs.center-xs
    .col.s12.m6
      .card-panel.grey.lighten-5.z-depth-1
        .row.valign-wrapper
          -unless @usuario==nil
            .col.s12.center
              = image_tag @usuario.avatar.url(:medium), :class => "circle responsive-img"
            .col.s10
              %span.black-text
                %h2
                  =@usuario.name
                  =@usuario.last_name
                %strong
                  =@usuario.email
                | DNI:
                =@usuario.dni
                | Edad: 
                -unless @usuario.birth_date==nil
                  =edad = Time.now.strftime("%Y").to_i - @usuario.birth_date.strftime("%Y").to_i
                años

          -else
            .col.center
              USUARIO NO REGISTRADO. Recordarle que obtendrá beneficios si está registrado.
    .col.s12.m6
      .card
        .card-content
          .card-title.center
            %h2 CARGAR (+) O CONSUMIR (-)
          .card-actions
            -if @card.status == 1
              - estado = "1- ACTIVADA"
              .row.center-xs
                = render 'transactions/form', transaction: @transaction
            -else
              -if @card.status == 2
                - estado = "2- ROBADA/ PERDIDA"
              -else
                -if @card.status == 3
                  - estado = "3- EN PROCESO DE FABRICACIÓN / ENVÍO"
                -else
                  -if @card.status == 4
                    - estado = "4 - ENTREGADA E INACTIVA"
                  -else
                    - estado = "INACTIVA"      
              %strong         
                Estado de la tarjeta: #{estado}
              %p Para activar nuevamente, presione EDITAR y cambie el valor de ESTADO por 1 - ACTIVADA.
  .row
    .col.s12.m6
      .card.center
        .card-content
          .card-title
            %h2 SALDO ACTUAL
          .card-actions
            %i.material-icons.medium monetization_on
            %span.money.black-text
              = (@card.credit1.to_f)/100
    .col.s12.m6
      .card.center
        .card-content
          .card-title
            %h2 PUNTAJE ACTUAL
          .card-actions
            %i.material-icons.medium bubble_chart
            %span.money.black-text
              = (@card.credit2)

  .row.center-xs
    = link_to 'Cambiar estado', edit_company_card_path(@company,@card), :class=> "btn"
    = link_to 'Ver movimientos', company_card_transactions_path(@company,@card), :class=> "btn"
    =link_to "Volver", company_panel_path(@company), :class=> "btn"
    -#= link_to 'Back', company_cards_path
      