config/routes.rb
Rails.application.routes.draw do
  
  
  resources :profiles, as: :users, only: [:show, :update]
  
  #devise_for :users, controllers: {registrations: "registrations"}
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  #Redireccionar c a companies
  get '/c/:id', to: redirect('/companies/%{id}')
  
  resources :companies do
  	resources :cards do
      resources :transactions
    end
    #Entorno de trabajo
    get 'panel', to: 'cards#scan'
    post 'panel', to: 'cards#scan'
    get 'prueba', to: 'companies#freeTrial'
    get 'stats', to: 'companies#stats'
    get 'requestCard', to: 'companies#send_mail_card_request'
  
  end

  #Ruta para asignar usuario a tarjeta existente
  post 'asignar', to: 'cards#asignuser'
  

  #Mostrar INDEX si está logueado
  authenticated :user do
  	root 'main#index'
  end
  
  #Mostrar página de aterrizaje si no está logueado
  unauthenticated :user do
  	devise_scope :user do
  		root 'main#landing'
  	end
  end

  #Rutas dinámicas para nombres de usuario de las compañías
  #datos = Company.all
  
  #datos.each do |c|
    #A menos que el alias esté vacío...
  #  unless c.alias == nil
  #    get c.alias, to: 'companies#show', :id => c.id    
  #  end
  #end
  

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_action :set_company_card
  before_action :authenticate_admin!, only: [:destroy]
  before_action :authenticate_owner!, only: [:new, :create, :edit, :update]

  # GET /transactions
  # GET /transactions.json
  def index

    #Sólo se puede ver si está logueado como OWNER del company_id asociado a la CARD
    # o como USUARIO asociado a la tarjeta.
    unless current_user.id==@card.user
      unless (@company.admin == current_user.id)
        unless current_user.is_admin?
           redirect_to root_path, notice: "No estás autorizado a ver las transacciones de esta tarjeta."
        end
      end
    end

    @transactions = Transaction.where(card: @card, company: @company).order("created_at DESC")
    
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    set_company_card
    @transaction = Transaction.new(transaction_params)
    
    @transaction.company = @company
    @transaction.card = @card
    @transaction.user = current_user

    if params[:cargar] == "Saldo"
      if params[:commit] == "Confirmar"
        @card.credit1 = @card.credit1.to_i+transaction_params[:amount].to_i
        if transaction_params[:amount].to_i<0
          @transaction[:description] = "Consumo de saldo"
        else
          @transaction[:description] = "Carga de saldo"
        end
      end
      if params[:commit] == "+"
        @card.credit1 = @card.credit1.to_i+transaction_params[:amount].to_i
        @transaction[:description] = "Carga de saldo"
      end
      if params[:commit] == "-"
        @card.credit1 = @card.credit1.to_i-transaction_params[:amount].to_i
        @transaction[:description] = "Consumo de saldo"
      end
    end

    if params[:cargar] == "Puntos"
      if params[:commit] == "Confirmar"
        @card.credit2 = @card.credit2.to_i+transaction_params[:amount].to_i
        if transaction_params[:amount].to_i<0
          @transaction[:description] = "Consumo de puntos"
        else
          @transaction[:description] = "Carga de puntos"
        end
      end
      if params[:commit] == "+"
        @card.credit2 = @card.credit2.to_i+transaction_params[:amount].to_i
        @transaction[:description] = "Carga de puntos"
      end
      if params[:commit] == "-"
        @card.credit2 = @card.credit2.to_i-transaction_params[:amount].to_i
        @transaction[:description] = "Consumo de Puntos"
      end
    end

    if @card.save
      respond_to do |format|
        if @transaction.save
          format.html { redirect_to company_panel_path(@company), notice: '*T* Se generó la transacción correctamente. <h2 class="red-text center">El cliente tiene ahora un saldo de <span class="grantexto"><br><br><br>$' + ((@card.credit1.to_f)/100).to_s + '|' + (@card.credit2).to_s + ' p</span></h2><br>' }
          format.json { render :show, status: :created, location: @transaction }
        else
          format.html { render :new }
          format.json { render json: @transaction.errors, status: :unprocessable_entity }
        end
      end
    else
      format.html { render :new  }
      format.json { render json: @card.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:card_id, :company_id, :user_id, :amount, :description)
    end

    def set_company_card
      @company = Company.find(params[:company_id]) 
      @card = Card.find(params[:card_id]) 
    end

    def verify_own_id
      unless (@company.admin == current_user.id)
        unless current_user.is_admin?
           redirect_to root_path, notice: "No estás autorizado a ver esto."
        end
      end
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.haml
= form_for([@company,@card, @transaction]) do |form|
  -if transaction.errors.any?
    #error_explanation
      %h2
        = pluralize(transaction.errors.count, "error")
        prohibited this transaction from being saved:
      %ul
        -transaction.errors.full_messages.each do |message|
          %li
            = message
  .row.center
    .col.s12
      = form.label "Monto en CENTAVOS o CANTIDAD de puntos"
      = form.number_field :amount, id: :transaction_amount

  .row
    .col-xs-12
      =select_tag "cargar", options_for_select(["Saldo", "Puntos"], "Saldo"), :class => "browser-default"

        

  .row.hide-on-med-and-down.center-xs
    = form.submit "Confirmar",:class=> "btn"

  .row.hide-on-large-only
    .col-xs-6
      =form.submit "+", :class=> "btn-floating btn-large waves-light green"
    .col-xs-6
      =form.submit "-", :class=> "btn-floating btn-large waves-light red"
/
  .row.red.center.hide-on-med-and-down
    .white-text
      %strong No olvide que debe ingresar la cantidad en centavos.
      %br
      Por ejemplo, 25 para recargar $0,25
      %br
      125 para recargar $1,25
      %br
      10000 para recargar $100
      %br
      %strong También debe anteponer el signo menos (-) para debitar una compra.
      %br
      Por ejemplo, -250, para debitar una compra de $2,50.

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.haml
%h1.center Movimientos
.container.cajita
  .col.s12.m8.l6
    %table.striped
      %thead
        %tr
          %th Fecha
          %th Hora
          %th Tipo de operación
          %th Monto
          %th{:colspan=>"3"}

      %tbody
        - @transactions.each do |transaction|
          %tr
            %td
              = transaction.created_at.strftime("%d/%m/%Y")
            %td
              = transaction.created_at.strftime("%H:%M")
            %td
              %small
                = transaction.description 
              - monto = transaction.amount
              -unless monto == nil
                -if monto<0
                  .red-text Compra
                  %td.red-text
                    $
                    = (monto.to_f/100).abs
                -else
                  .green-text Recarga
                  %td.green-text
                    $
                    = (monto.to_f/100).abs

    .center
      = link_to 'Volver', :back, :class=> "btn"

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Card:</strong>
  <%= @transaction.card %>
</p>

<p>
  <strong>Company:</strong>
  <%= @transaction.company %>
</p>

<p>
  <strong>User:</strong>
  <%= @transaction.user %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Description:</strong>
  <%= @transaction.description %>
</p>

<%= link_to 'Edit', edit_company_card_transaction_path(@company,@card,@transaction) %> |
<%= link_to 'Back', company_card_transactions_path %>

app/views/transactions/viejoindex.html.erb
%h1 Movimientos

%table
  %thead
    %tr
      %th Card
      %th Company
      %th User
      %th Amount
      %th Description
      %th{:colspan=>"3"}

  %tbody
    - @transactions.each do |transaction|
      %tr
        %td
          = transaction.card 
        %td
          = transaction.company 
        %td
          = transaction.user 
        %td
          = transaction.amount 
        %td
          = transaction.description 
        %td
          = link_to 'Show', company_card_transaction_path(@company,@card,transaction) 
        %td
          = link_to 'Edit', edit_company_card_transaction_path(@company,@card,transaction) 
        %td
          = link_to 'Destroy', company_card_transaction_path(@company,@card,transaction), method: :delete, data: { confirm: 'Are you sure?' } 
 
<br>

= link_to 'New Transaction', new_company_card_transaction_path